package allin.model

object ApiMessage {
    const val WELCOME = "Welcome on AllIn's API !"
    const val TOKEN_USER_NOT_FOUND = "User not found with the valid token !"
    const val USER_NOT_FOUND = "User not found."
    const val BET_NOT_FOUND = "Bet not found."
    const val BET_ALREADY_EXIST = "Bet already exists."
    const val INCORRECT_LOGIN_PASSWORD = "Login and/or password incorrect."
    const val USER_ALREADY_EXISTS = "Username already exists."
    const val MAIL_ALREADY_EXISTS = "Mail already exists."
    const val INVALID_MAIL = "Invalid mail."
    const val PARTICIPATION_NOT_FOUND = "Participation not found."
    const val NOT_ENOUGH_COINS = "Not enough coins."
    const val NO_GIFT = "Can't get daily gift."
    const val USER_CANT_BE_DELETE = "This user can't be delete now !"
    const val FRIENDS_ALREADY_EXISTS = "User already exists in your Friends List."
    const val FRIENDS_DOESNT_EXISTS = "User doesn't exists in your Friends List."
    const val FRIENDS_REQUEST_HIMSELF = "The receiver can't be the sender."
    const val FILE_NOT_FOUND = "File not found."
    const val USER_DOESNT_HAVE_PERMISSION = "This user can't delete or modify this."
    const val JWT_TOKEN_INFO = "JWT token of the logged user"
    const val ID_BET_INFO = "Id of the desired bet"
    const val BET_NOT_FOUND_INFO = "Bet not found in the selected source"
    const val NOT_CREATOR_INFO = "The user is not the creator of the bet"
    const val USER_UPDATE_INFO = "New User information"
}